# Generated by Django 2.2.4 on 2021-01-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210113_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='application.User')),
            ],
        ),
    ]
